### ISSUE TITLE
flr 相機沒反應

### ISSUE THREAD

**Issue by minmoon1225** [raspberrypi-tw/meetup19#1]
VIDEOIO ERROR: V4L: can't open camera by index 1

**Comment by raspberrypi-tw** [comment]
如果執行 flir_preview.py 出現 VIDEOIO ERROR: V4L: can't open camera by index 1 錯誤訊息，要確定以下幾點
1. 是否已經接了 Raspberry Pi Camera？ ==> 要接
2. 在 ~/LeptonModule/software/v4l2lepton 的 v4l2lepton.cpp，是否都修改為 /dev/video1？ ==> 要修改成 /dev/video1 
3. 在 ~/LeptonModule/software/v4l2lepton 是否有先執行 sudo ./v4l2lepton /dev/video1？ ==> 要先執行

之後就可以再開另一個終端機，執行 flir_preview.py

**Comment by minmoon1225** [comment]
都改了 但我第3步執行失敗 出現這個 
sudo ./v4l2lepton command not found

**Comment by raspberrypi-tw** [comment]
出現 "sudo ./v4l2lepton command not found" 表示沒有 v4l2lepton，所以需要完成編譯如下。
$ cd ~/LeptonModule/software/v4l2lepton
$ sed -i -e 's/video0/video1/g' v4l2lepton.cpp
$ make
$ sudo ./v4l2lepton -d /dev/spidev0.0 /dev/video1

**Comment by minmoon1225** [comment]
執行完出現這串

Failed to open v4l2sink device. (No such file or directory)

**Comment by raspberrypi-tw** [comment]
"Failed to open v4l2sink device" 可能是您的 FLIR 相機沒有偵測到，或是您 SPI Device 沒有啟動，或是您的 /dev/videoX 數字不正確等都有可能。
這要先確認相機模組是否有安裝好，還有 FLIR 相機是否有安裝好才行。

**Comment by minmoon1225** [comment]
因為執行raspberrypi_video時可以出現畫面 只是會有殘影  所以在想會不會是哪一步做錯所以才沒偵測到FLIR 相機 
SPI Device要是沒啟動 那raspberrypi_video也沒辦法跑出畫面吧? 我不太清楚
/dev/videoX 數字這方面我也試過0~15這些數字我都試過了 還是跑不出畫面
不知道是我本身樹莓派有問題還是安裝套件時哪裡出了問題 我困惑了很久估計有2個月 所以我才上前求助您 
我也知道這樣沒有畫面很難幫我解決問題 但我不知道還能用什麼方法聯繫您

**Comment by raspberrypi-tw** [comment]
如果執行 raspberrypi_video 有畫面應該就有接對，殘影是其他問題。

如果是要看畫面或是讀取數值，可以直接用 pylepton，不一定要使用 v4l2lepton
https://github.com/groupgets/pylepton
